<?php
defined('BASEPATH') or exit('No direct script access allowed');
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
if ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || $_SERVER['SERVER_PORT'] == 443) {
	define('BASE_URL', 'https://marketplace.goepicware.com/');
} else {
	define('BASE_URL', 'http://marketplace.goepicware.com/');
}
define('CLIENT_PANEL', 'camppanel');
define('CALLCENTER_PANEL', 'callcenter');
define('BUSINESS_PANEL', 'businesspanel');
define('CARPAL_API_URL', 'https://api.carpal.me/v2/');
define('CARPAL_API_USERNAME', 'demo@carpal.me');
define('CARPAL_API_PASSWORD', 'carpaldemo');
define('S3_LINK', 'http://ninjaos.s3.amazonaws.com/');


define('LALAMOVE_API', 'https://rest.lalamove.com/v2/');
/*
define('LALAMOVE_API','https://rest.lalamove.com/v2/');
define('LALAMOVE_API_SECRET','MCsCAQACBQCGOP9tAgMBAAECBEiHRCECAwDV9QIDAKCZAgIlgQICfukCAl1O');
define('LALAMOVE_API_KEY','4bee4f58739149bdb1f26e085d4e185b');
*/
/*
define('LALAMOVE_API','https://sandbox-rest.lalamove.com/v2/');

define('LALAMOVE_API_SECRET','MC0CAQACBQDuizuxAgMBAAECBQDBHcPpAgMA+GMCAwD12wIDANp3AgJ5LQICTdA=');
define('LALAMOVE_API_KEY','0f7cc944d7be42ec95bfebe927611d40');
*/

$config['base_url'] = BASE_URL;
$config['api_url'] = BASE_URL . "api/";
$config['camp_url'] = BASE_URL . CLIENT_PANEL . "/";
$config['callcenter_url'] = BASE_URL . CALLCENTER_PANEL . "/";
$config['business_url'] = BASE_URL . BUSINESS_PANEL . "/";
$config['admin_url'] = BASE_URL . "ncadminpanel/";
$config['skin_url'] = BASE_URL . 'skin/froentend/';
$config['callcenter_skin_url'] = BASE_URL . 'skin/froentend/callcenter/';
$config['admin_skin'] = BASE_URL . 'skin/backend/';
$config['load_lib'] = BASE_URL . 'lib/';
$config['load_font'] = BASE_URL . 'fonts/';
$config['media_url'] = BASE_URL . 'media/';
$config['s3_link'] = S3_LINK;


/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
// $config['encryption_key'] = 'DFE^%^&*&cznbseu62532u@$%^&*%xcjhf2765435$%&%$ZFDFT#$%';
$config['encryption_key'] = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 28800;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 28800;
$config['sess_regenerate_destroy'] = FALSE;




/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'secure_key';
$config['csrf_cookie_name'] = 'secure_cookie_name';
$config['csrf_expire'] = 28800;
$config['csrf_regenerate'] = FALSE;
$config['csrf_exclude_uris'] = array(

	'api/v1.1/orders/submit_order',
	'api/v1.1/orderstest/submit_order',
	'api/v1.1/OrdersSrn/submit_order',
	'api/v1.1/orders/submit_order_test',
	'api/v1.1/orders/submit_temp_order',
	'api/v1.1/orders/payment_status_update',
	'api/v1.1/orders/payment_status_check',
	'api/v1.1/cateringorders/submit_order',
	'api/v1.1/cateringorders/submit_order_test',
	'api/v1.1/cateringorders/submit_temp_order',
	'api/v1.1/cateringorders/payment_status_update',
	'api/v1.1/cateringorders/payment_status_check',
	'api/v1.1/cateringorders/request_catering',
	'api/v1.1/cateringorders/quotation_request',
	'api/v1.1/cateringordersv1/submit_order',
	'api/v1.1/cart/insert',
	'api/v1.1/cart/update',
	'api/v1.1/cart/delete',
	'api/v1.1/cart/contents',
	'api/v1.1/cart/update_customer_info',
	'api/v1.1/cart/destroy',
	'api/v1.1/cartver2/insert',
	'api/v1.1/cartver2/update',
	'api/v1.1/cartver2/delete',
	'api/v1.1/cartver2/contents',
	'api/v1.1/cartver2/update_customer_info',
	'api/v1.1/cartver2/destroy',
	'api/v1.1/carttest/insert',
	'api/v1.1/carttest/update',
	'api/v1.1/carttest/delete',
	'api/v1.1/carttest/contents',
	'api/v1.1/carttest/update_customer_info',
	'api/v1.1/customer/login',
	'api/v1.1/customer/logout',
	'api/v1.1/customer/fblogin',
	'api/v1.1/customer/fbloginapp',
	'api/v1.1/customer/facebook_registration',
	'api/v1.1/customer/registration',
	'api/v1.1/customer/updateprofile',
	'api/v1.1/customer/secondary_address',
	'api/v1.1/customer/callcenter_updateprofile',
	'api/v1.2/customer/callcenter_updateprofile',
	'api/v1.1/customer/callcenter_catering_updateprofile',
	'api/v1.1/customer/updateprofile',
	'api/v1.1/customer/forgot_password',
	'api/v1.1/customer/changepassword',
	'api/v1.1/customer/resetpassword',
	'api/v1.1/customer/activation',
	'api/v1.1/customer/email_exist',
	'api/v1.1/customer/phoneno_exist',
	'api/v1.1/customer/update_notification_status',
	'api/v1.1/promotion/get_promotion_detail',
	'api/v1.1/promotion/voucher',
	'api/v1.1/Promotion_api_v1/apply_voucher',
	'api/v1.1/promotion/get_promotion',
	'api/v1.1/customer/secondary_address_edit',
	'api/v1.1/customer/secondary_address_add',
	'api/v1.1/customer/secondary_address_remove',
	'api/v1.1/customer/loginById',
	'api/v1.1/orders/cancel_order',
	'api/v1.1/Promotion_api_v1/apply_loyality',
	'api/v1.1/Loyalty/apply_loyality',
	'api/v1.1/Loyalty/apply_loyalityv1',
	'api/v1.1/Productadditional/addwishlist',
	'api/v1.1/promotion/user_promotion',
	'api/v1.1/promotion/promo_popup_enable',
	'api/v1.1/Promotion_api_v1/apply_promotion',
	'api/v1.1/cms/newsletter',
	'api/v1.1/review/reviewinsert',
	'api/v1.1/customer/updatebilladdress',
	'api/v1.1/customer/shippingaddress',
	'api/v1.1/customer/updateshippingaddress',
	'api/v1.1/newsletter/facebookuser_newsletter_subscriber',
	'api/v1.1/contactus/contact_us',
	'api/v1.1/contactus/careers',
	'api/v1.1/contactus/temp_catering_booking',
	'api/v1.1/contactus/temp_reservation_booking',
	'api/v1.1/businesscall/login',
	'api/v1.1/businesscall/devicetoken_update_home',
	'api/v1.1/businesscall/logout',
	'api/v1.1/businesscall/changetime',
	'api/v1.1/businesscall/change_outlet_status',
	'api/v1.1/businesscall/change_status_random',
	'api/v1.1/businesscall/change_orderstatus_popup',
	'api/v1.1/businesscall/change_orderstatus_popup_smartsend',
	'api/v1.1/businesscall/assign_rider',
	'api/v1.1/businesscall/rider_add',
	'api/v1.1/businesscall/rider_update',
	'api/v1.1/businesscall/order_details',
	'api/v1.1/businesscall/changeOutlet',
	'api/v1.1/businesscall/smartsendOrder',
	'api/v1.1/businesscall/smartsendTrack',
	'api/v1.1/businesscall/updateCashPayment',
	'api/v1.1/cateringcart/insert',
	'api/v1.1/cateringcart/update',
	'api/v1.1/cateringcart/delete',
	'api/v1.1/cateringcart/delete_individual',
	'api/v1.1/cateringcart/update_individual',
	'api/v1.1/cateringcart/contents',
	'api/v1.1/cateringcart/update_customer_info',
	'api/v1.1/cateringcart/destroy',
	'api/v1.1/tablemanagement/find_table',
	'api/v1.1/businesscall/all_rider_list',
	'api/v1.1/businesscall/api_delivary_order_creation',
	'api/v1.1/businesscall/updateLalamoveOrderDetails',
	'api/v1.1/businesscall/removeLalamoveOrder',
	'api/v1.1/reservation/reservation_availability_days_status',
	'api/v1.1/reservation/reservation_availabilitydate_with_closeddate',
	'api/v1.1/reservation/reservation_availabilitydate_with_closeddate1',
	'api/v1.1/reservation/reservation_availability_times_new',
	'api/v1.1/reservation/reservation_availability_times_new1',
	'api/v1.1/reservation/reservation_shop_closed_dates',
	'api/v1.1/reservation/reservation_availability_times',
	'api/v1.1/reservation/reservation_suggest_accept',
	'api/v1.1/reservation/reservation_suggest_reject',
	'api/v1.1/reservation/reservation_submit_order',
	'api/v1.1/reservation1/reservation_submit_order',
	'api/v1.1/reservation1/reservation_availability_times_new',
	'api/v1.1/reservation1/reservation_availability_times_new1',
	'api/v1.1/reservation1/reservation_availabilitydate_with_closeddate',
	'api/v1.1/reservation1/reservation_availabilitydate_with_closeddate1',
	'api/v1.1/reservation1/reservation_send_email',
	'api/v1.1/payment/stripeTokenPay',
	'api/v1.1/payment/captureAmount',
	'api/v1.1/payment/updateStripeId',
	'api/v1.1/payment/savedCards',
	'api/v1.1/payment/deleteCard',
	'api/v1.1/payment/authOmise',
	'api/v1.1/payment/captureAmountOmise',
	'api/v1.1/ordersv1/submit_order',
	'api/v1.1/ordersv1/closePayment',
	'api/v1.1/reddot/makeReddotPayment',
	'api/v1.1/reddot/makeReddotPayRedirct',
	'api/v1.1/reddot/reddotPaymentLog',
	'api/v1.1/wirecard/makeWirecardPay',
	'api/v1.1/wirecard/wirecardPaymentLog',
	'api/v1.1/ordersv1/orderEventredeem',

	'api/v1.1/promotion_api_v2/apply_voucher',
	'api/v1.1/promotion_api_v2/apply_loyality',
	'api/v1.1/promotion_api_v2/apply_promotion',
	'api/v1.1/promotion_api_v2/claimpromo',

	'api/v1.1/reports/activity_counts',

	'api/v1.1/cateringproducts/catering_availabilitydate_with_closeddate',
	'api/v1.1/cateringproducts/catering_availability_time',

	'api/v1.1/cateringorders/quotation_request',
	'api/v1.1/cateringorders/download_quotation',
	'api/v1.1/cateringorders/download_corporate_quotation',
	'api/v1.1/cateringcart/corpoate_delete',
	'api/v1.1/cateringcart/corporate_insert',
	'api/v1.1/cateringproducts/catering_products_update_detail',
	'api/v1.2/cart/simpleCartInsert',
	'api/v1.2/simplecart/simpleProductCartInsert',
	'api/v1.2/cart/update',
	'api/v1.2/catering/availableTime',
	'api/v1.2/cateringcart/insert',
	'api/v1.2/cateringcart/update',
	'api/v1.2/cateringcart/updateBreakTime',
	'api/v1.2/cateringcart/delete',
	'api/v1.2/cateringcart/delete_individual',
	'api/v1.2/cateringcart/destroy',
	'api/v1.2/cateringcart/downloadQtnWithoutCart',
	'api/v1.2/cateringorders/submit_order',
	'api/v1.2/cateringorders/request_catering',
	'api/v1.2/payment/stripeTokenPay',
	'api/v1.1/products/favourite_products_add',
	'api/v1.1/paypallogmonitoring/add_log',
	'api/v1.1/orders/check_callcenter_order_existing',
	'api/v1.1/contactus/feedback_us',
	'api/v1.1/orders/user_order_rating',
	'api/v1.1/GusestAccount/create',
	'api/v1.1/ordersv1/user_order_rating',
	'api/v1.1/orderstest/submit_order',
	'api/v1.1/guestaccount/create',
	'api/v1.1/guestaccount/guest_customer_phone',
	'api/v1.1/ordersv1/send_pos_orders',
	'api/v1.2/cart/cart_edit_item',
	'api/v1.1/cart/cart_edit_item',
	'api/v1.1/callcenterapi/v1.1/login',
	'api/v1.1/orders/draft_order',
	'api/v1.1/cart/updatecartprice',
	'api/v1.2/cart/addmenuproductcart',
	'api/v1.1/stripeclientpayment/clientpayment',
	'api/v1.1/advancepayments/recordPayment',
	'api/v1.1/uob/sessionId',
	'api/v1.1/cybersource/signature_value',
	'api/v1.1/cybersource/payment_responce',
	'api/v1.1/customer/send_customer_otp',
	'api/v1.1/customer/customer_otp_verification',
	'api/v1.1/customer/resend_otp',
	'api/v1.1/payment/omise_search_details',
	'api/v1.1/payment/retrieve_charge_details',
	'api/v1.1/omisepaymentcapture/capture',

	'api/orders/submit_order',
	'api/orderstest/submit_order',
	'api/OrdersSrn/submit_order',
	'api/orders/submit_order_test',
	'api/orders/submit_temp_order',
	'api/orders/payment_status_update',
	'api/orders/payment_status_check',
	'api/cateringorders/submit_order',
	'api/cateringorders/submit_order_test',
	'api/cateringorders/submit_temp_order',
	'api/cateringorders/payment_status_update',
	'api/cateringorders/payment_status_check',
	'api/cateringorders/request_catering',
	'api/cateringorders/quotation_request',
	'api/cateringordersv1/submit_order',
	'api/cart/insert',
	'api/cart/update',
	'api/cart/delete',
	'api/cart/contents',
	'api/cart/update_customer_info',
	'api/cart/destroy',
	'api/cartver2/insert',
	'api/cartver2/update',
	'api/cartver2/delete',
	'api/cartver2/contents',
	'api/cartver2/update_customer_info',
	'api/cartver2/destroy',
	'api/carttest/insert',
	'api/carttest/update',
	'api/carttest/delete',
	'api/carttest/contents',
	'api/carttest/update_customer_info',
	'api/cart/create_group',
	'api/cart/confirm_group',
	'api/cart/cancel_group',
	'api/customer/login',
	'api/customer/logout',
	'api/customer/fblogin',
	'api/customer/fbloginapp',
	'api/customer/googleloginapp',
	'api/customer/facebook_registration',
	'api/customer/registration',
	'api/customer/updateprofile',
	'api/customer/secondary_address',
	'api/customer/callcenter_updateprofile',
	'apiv2/customer/callcenter_updateprofile',
	'api/customer/callcenter_catering_updateprofile',
	'api/customer/updateprofile',
	'api/customer/forgot_password',
	'api/customer/changepassword',
	'api/customer/resetpassword',
	'api/customer/activation',
	'api/customer/email_exist',
	'api/customer/phoneno_exist',
	'api/customer/update_notification_status',
	'api/promotion/get_promotion_detail',
	'api/promotion/voucher',
	'api/Promotion_api_v1/apply_voucher',
	'api/promotion/get_promotion',
	'api/customer/secondary_address_edit',
	'api/customer/secondary_address_add',
	'api/customer/secondary_address_remove',
	'api/customer/loginById',
	'api/orders/cancel_order',
	'api/Promotion_api_v1/apply_loyality',
	'api/Loyalty/apply_loyality',
	'api/Loyalty/apply_loyalityv1',
	'api/Productadditional/addwishlist',
	'api/promotion/user_promotion',
	'api/promotion/promo_popup_enable',
	'api/Promotion_api_v1/apply_promotion',
	'api/cms/newsletter',
	'api/review/reviewinsert',
	'api/customer/updatebilladdress',
	'api/customer/shippingaddress',
	'api/customer/updateshippingaddress',
	'api/newsletter/facebookuser_newsletter_subscriber',
	'api/contactus/contact_us',
	'api/contactus/careers',
	'api/contactus/temp_catering_booking',
	'api/contactus/temp_reservation_booking',
	'api/businesscall/login',
	'api/businesscall/devicetoken_update_home',
	'api/businesscall/logout',
	'api/businesscall/changetime',
	'api/businesscall/change_outlet_status',
	'api/businesscall/change_status_random',
	'api/businesscall/change_orderstatus_popup',
	'api/businesscall/change_orderstatus_popup_smartsend',
	'api/businesscall/assign_rider',
	'api/businesscall/rider_add',
	'api/businesscall/rider_update',
	'api/businesscall/order_details',
	'api/businesscall/changeOutlet',
	'api/businesscall/smartsendOrder',
	'api/businesscall/smartsendTrack',
	'api/businesscall/updateCashPayment',
	'api/businesscall/orders_outlet_status',
	'api/businesscall/orders_outlet_random_status',
	'api/cateringcart/insert',
	'api/cateringcart/update',
	'api/cateringcart/delete',
	'api/cateringcart/delete_individual',
	'api/cateringcart/update_individual',
	'api/cateringcart/contents',
	'api/cateringcart/update_customer_info',
	'api/cateringcart/destroy',
	'api/tablemanagement/find_table',
	'ninjapro/orders/submit_order',
	'ninjapro/ordersv1/submit_order',
	'ninjapro/payment/stripeTokenPay',
	'ninjapro/paymentV2/stripeTokenPay',
	'ninjapro/paymentV2/captureAmount',
	'ninjapro/paymentV3/stripeTokenPay',
	'ninjapro/paymentV3/captureAmount',
	'ninjapro/cart/insert',
	'ninjapro/cartv2/insert',
	'ninjapro/customer/forgot_password',
	'ninjapro/reservation/reservation_availability_timesninjapro',
	'api/businesscall/all_rider_list',
	'api/businesscall/api_delivary_order_creation',
	'api/businesscall/updateLalamoveOrderDetails',
	'api/businesscall/removeLalamoveOrder',
	'api/businesscall/updateLalamoveOrderStatus',
	'api/reservation/reservation_availability_days_status',
	'api/reservation/reservation_availabilitydate_with_closeddate',
	'api/reservation/reservation_availabilitydate_with_closeddate1',
	'api/reservation/reservation_availability_times_new',
	'api/reservation/reservation_availability_times_new1',
	'api/reservation/reservation_shop_closed_dates',
	'api/reservation/reservation_availability_times',
	'api/reservation/reservation_suggest_accept',
	'api/reservation/reservation_suggest_reject',
	'api/reservation/reservation_submit_order',
	'api/reservation1/reservation_submit_order',
	'api/reservation1/reservation_availability_times_new',
	'api/reservation1/reservation_availability_times_new1',
	'api/reservation1/reservation_availabilitydate_with_closeddate',
	'api/reservation1/reservation_availabilitydate_with_closeddate1',
	'api/reservation1/reservation_send_email',
	'georges_pos/webservice',
	'georges_pos/webservice/register',
	'georges_pos/webservice/memberregister_check',
	'georges_pos/webservice/memberinfo',
	'cravenasipos/posorder/order',
	'springcourt_pos/webservice',
	'springcourt_pos/webservice/register',
	'springcourt_pos/webservice/memberregister_check',
	'springcourt_pos/webservice/memberinfo',

	'muthuscurry_pos/webservice',
	'muthuscurry_pos/webservice/register',
	'muthuscurry_pos/webservice/memberregister_check',
	'muthuscurry_pos/webservice/memberinfo',

	'api/ascentiscrm/memberEnquiry',

	'api/payment/stripeTokenPay',
	'api/payment/captureAmount',
	'api/payment/updateStripeId',
	'api/payment/savedCards',
	'api/payment/deleteCard',
	'api/payment/authOmise',
	'api/payment/captureAmountOmise',

	'api/paymentv1/getPaymentReferenceId',
	'api/paymentv1/authOmise',
	'api/paymentv1/captureAmountOmise',

	'api/ordersv1/submit_order',
	'api/ordersv1/closePayment',
	'api/reddot/makeReddotPayment',
	'api/reddot/makeReddotPayRedirct',
	'api/reddot/reddotPaymentLog',
	'api/wirecard/makeWirecardPay',
	'api/wirecard/wirecardPaymentLog',
	'api/ordersv1/orderEventredeem',

	'api/promotion_api_v2/apply_voucher',
	'api/promotion_api_v2/apply_loyality',
	'api/promotion_api_v2/apply_promotion',
	'api/promotion_api_v2/claimpromo',

	'api/reports/activity_counts',

	'api/cateringproducts/catering_availabilitydate_with_closeddate',
	'api/cateringproducts/catering_availability_time',

	'api/cateringorders/quotation_request',
	'api/cateringorders/download_quotation',
	'api/cateringorders/download_corporate_quotation',
	'api/cateringcart/corpoate_delete',
	'api/cateringcart/corporate_insert',
	'api/cateringproducts/catering_products_update_detail',
	'apiv2/cart/simpleCartInsert',
	'apiv2/simplecart/simpleProductCartInsert',
	'apiv2/cart/update',
	'apiv2/catering/availableTime',
	'apiv2/cateringcart/insert',
	'apiv2/cateringcart/update',
	'apiv2/cateringcart/updateBreakTime',
	'apiv2/cateringcart/delete',
	'apiv2/cateringcart/delete_individual',
	'apiv2/cateringcart/destroy',
	'apiv2/cateringcart/downloadQtnWithoutCart',
	'apiv2/cateringorders/submit_order',
	'apiv2/cateringorders/request_catering',
	'apiv2/payment/stripeTokenPay',
	'ncadminpanel/stripepayment',
	'api/products/favourite_products_add',
	'api/paypallogmonitoring/add_log',
	'api/orders/check_callcenter_order_existing',
	'api/contactus/feedback_us',
	'api/orders/user_order_rating',
	'api/GusestAccount/create',
	'api/ordersv1/user_order_rating',
	'api/orderstest/submit_order',
	'api/guestaccount/create',
	'api/guestaccount/guest_customer_phone',
	'api/ordersv1/send_pos_orders',
	'apiv2/cart/cart_edit_item',
	'api/cart/cart_edit_item',
	'api/callcenterapi/login',
	'api/orders/draft_order',
	'api/cart/updatecartprice',
	'apiv2/cart/addmenuproductcart',
	'account/reddotnotify',
	'api/stripeclientpayment/clientpayment',
	'api/advancepayments/recordPayment',
	'account/wirecardstatus',
	'api/uob/sessionId',

	'cateringv2/cart/insert',
	'cateringv2/cart/update',
	'cateringv2/cart/delete',
	'cateringv2/cart/uploadImg',
	'cateringv2/cart/delete_individual',
	'cateringv2/orders/submit_order',
	'cateringv2/catering/availableTime',
	'cateringv2/payment/omiseTokenPay',
	'cateringv2/contactus/contact_us',
	'cateringv2/cart/updateBreakTime',
	'analytics/analytics/productWhoboughtdetails',
	'api/cybersource/signature_value',
	'api/cybersource/payment_responce',
	'api/payment/omise_search_details',
	'api/payment/retrieve_charge_details',
	'api/customer/send_customer_otp',
	'api/customer/customer_otp_verification',
	'api/customer/resend_otp',
	'api/omisepaymentcapture/capture',
	'api/Authentication/init',
	'api/paymentv1/captureAmountTwoCTwoP',
	'api/paymentv1/returnTwoCTwoP',
	'api/paymentv1/returnTwoCTwoPResult',
	'api/paymentv1/checkTwoCTwoP',
	'api/paymentv1/checkTwoCTwoPStatus',
	'api/formsdetails/foodbusiness',
	'api/formsdetails/signupride',
	'api/cart/insert_cart_without_product',
	'api/cart/removeGroupPendingList',
	'api/cart/removeGroupOrder',

	'api/pandago/fee_estimation',
	'api/pandago/time_estimation',
	'api/pandago/submit_order',
	'api/pandago/pandago_webhook',
	'api/pandago/cancel_pandago_order',
	'api/pandago/get_fee_and_estimation_time',

	'api/grabexpress/deliveries/create_deliveries',
	'api/grabexpress/deliveries/delivery_by_id',
	'api/grabexpress/deliveries/cancel_delivery',
	'api/grabexpress/deliveries/tracking_webhook',
	'api/grabexpress/deliveries/order_fees',

	'api/milkruncallback/order_status',
	'api/milkruncallback/milkrun_update_status',
	'api/businesscall/get_milkrun_order_details',
	'api/businesscall/milkrun_cancel',

	'api/milkruncallback/create_customer',
	'api/milkruncallback/alllanguages',

	'api/businesscall/pickupp_cancel',
	'api/pickuppcallback/order_status',

	'api/foodpanda_middleware/food_panda_order',
	'api/deliveryhero/index/order/[\s\S]*',

	'api/newsletter/subscription_new',

	'api/cart_new/insert',
	'api/cart_new/delete',
	'api/cart_new/update',
	'api/cart_new/destroy',
	'api/cart_new/is_voucher_insert',
	'api/ordersv1/add_voucher_redeem',
	'api/lalamovenotify/notification',

	'api/lalamove/lalamove_webhook',


	'api/mainadmin/admincontroller/login',
	'api/mainadmin/admincontroller/forgotpassword',
	'api/mainadmin/admincontroller/reset_password',

	'api/company/companycontroller/add',
	// 'api/company/companycontroller/edit/[\s\S]*',
	'api/company/companycontroller/edit',
	'api/company/companycontroller/company_delete',
	'api/company/companycontroller/login',

	'api/company/settings/edit',
	'api/company/userroles/add',
	'api/company/userroles/edit/[\s\S]*',
	'api/company/userroles/usergroup_delete',

	'api/company/availability/add',
	'api/company/availability/edit/[\s\S]*',
	'api/company/availability/action',

	'api/clientpanel/clients/login',

	'api/clientpanel/outlettags/add',
	'api/clientpanel/outlettags/update',
	'api/clientpanel/outlettags/action',
	'api/clientpanel/outlettags/delete',

	'api/clientpanel/outlets/add',
	'api/clientpanel/outlets/update',
	'api/clientpanel/outlets/action',
	'api/clientpanel/outlets/delete',
	'api/clientpanel/outlets/changeOutletStatus',

	'api/clientpanel/outletzone/add',
	'api/clientpanel/outletzone/update',
	'api/clientpanel/outletzone/action',
	'api/clientpanel/outletzone/delete',
	'api/clientpanel/outletzone/addmapdata',


	'api/clientpanel/category/add',
	'api/clientpanel/category/update',
	'api/clientpanel/category/action',
	'api/clientpanel/category/delete',

	'api/clientpanel/subcategory/add',
	'api/clientpanel/subcategory/update',
	'api/clientpanel/subcategory/action',
	'api/clientpanel/subcategory/delete',

	'api/clientpanel/products/add',
	'api/clientpanel/products/update',
	'api/clientpanel/products/action',
	'api/clientpanel/products/delete',
	'api/clientpanel/products/importsimple',
	'api/clientpanel/products/importcombo',

	'api/clientpanel/productgroup/add',
	'api/clientpanel/productgroup/update',
	'api/clientpanel/productgroup/action',
	'api/clientpanel/productgroup/delete',

	'api/clientpanel/sitelocation/add',
	'api/clientpanel/sitelocation/update',
	'api/clientpanel/sitelocation/action',
	'api/clientpanel/sitelocation/delete',

	'api/clientpanel/brands/add',
	'api/clientpanel/brands/update',
	'api/clientpanel/brands/action',
	'api/clientpanel/brands/delete',

	'api/clientpanel/menugroup/add',
	'api/clientpanel/menugroup/update',
	'api/clientpanel/menugroup/action',
	'api/clientpanel/menugroup/delete',

	'api/clientpanel/menuitem/add',
	'api/clientpanel/menuitem/update',
	'api/clientpanel/menuitem/action',
	'api/clientpanel/menuitem/delete',

	'api/clientpanel/pages/add',
	'api/clientpanel/pages/update',
	'api/clientpanel/pages/action',
	'api/clientpanel/pages/delete',

	'api/clientpanel/staticblocks/add',
	'api/clientpanel/staticblocks/update',
	'api/clientpanel/staticblocks/action',
	'api/clientpanel/staticblocks/delete',

	'api/clientpanel/faqcategory/add',
	'api/clientpanel/faqcategory/update',
	'api/clientpanel/faqcategory/action',
	'api/clientpanel/faqcategory/delete',

	'api/clientpanel/faqs/add',
	'api/clientpanel/faqs/update',
	'api/clientpanel/faqs/action',
	'api/clientpanel/faqs/delete',

	'api/clientpanel/emailtemplate/add',
	'api/clientpanel/emailtemplate/update',
	'api/clientpanel/emailtemplate/action',
	'api/clientpanel/emailtemplate/delete',

	'api/clientpanel/banner/add',
	'api/clientpanel/banner/update',
	'api/clientpanel/banner/action',
	'api/clientpanel/banner/delete',

	'api/clientpanel/userrole/add',
	'api/clientpanel/userrole/update',
	'api/clientpanel/userrole/action',
	'api/clientpanel/userrole/delete',

	'api/clientpanel/customer/add',
	'api/clientpanel/customer/update',
	'api/clientpanel/customer/action',
	'api/clientpanel/customer/delete',
	'api/clientpanel/customer/import',

	'api/clientpanel/promotion/add',
	'api/clientpanel/promotion/update',
	'api/clientpanel/promotion/action',
	'api/clientpanel/promotion/delete',

	'api/clientpanel/timeslot/add',
	'api/clientpanel/timeslot/update',
	'api/clientpanel/timeslot/action',
	'api/clientpanel/timeslot/delete',

	'api/clientpanel/users/add',
	'api/clientpanel/users/update',
	'api/clientpanel/users/action',
	'api/clientpanel/users/delete',
	'api/clientpanel/users/updatepassword',

	'api/clientpanel/tags/add',
	'api/clientpanel/tags/update',
	'api/clientpanel/tags/action',
	'api/clientpanel/tags/delete',

	'api/clientpanel/rider/add',
	'api/clientpanel/rider/update',
	'api/clientpanel/rider/action',
	'api/clientpanel/rider/delete',

	'api/clientpanel/orders/changeOrderStatus',
	'api/clientpanel/orders/changeOrderBulkStatus',
	'api/clientpanel/orders/updateorderdate',
	'api/clientpanel/rewardspoints/credit',
	'api/clientpanel/rewardspoints/debit',

	'api/clientpanel/clients/update',

	'api/clientpanel/holiday/add',
	'api/clientpanel/holiday/update',
	'api/clientpanel/holiday/action',
	'api/clientpanel/holiday/delete',

	'api/user/cart/createCart',
	'api/user/cart/updateCartItem',
	'api/user/cart/deleteCartItem',
	'api/user/cart/removeCart',

	'api/user/store/addFavourite',
	'api/user/store/removeFavourite',

	'api/user/orders/placeorder',

	'api/user/paymentuvcr/response',

	'api/user/address/addAddress',
	'api/user/customers/login',

	'api/user/deliverypartners/loadPartnersList',
	'api/user/deliverypartners/createPartnerOrder',
	'api/user/deliverypartners/confirmPartnerOrder',
	'api/user/deliverypartners/response',

	'api/user/paymentuvcr/processPayment',
	'api/user/paymentuvcr/checkPaymentStatus',

	'api/user/coupon/applyPromo',
	'api/user/orders/orderAgain',
);

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';
